openapi: '3.1.0'
info:
  title: API сервер для проекта «Шесть городов»
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов»
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
- name: offers
  description: Действия с объявлениями.
- name: comments
  description: Действия с комментариями.
- name: users
  description: Действия с пользователем.
paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true

      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
      responses:
        '200':
          description: Пользователь успешно авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        '400':
          description: Неверные данные для входа
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

      responses:
        '200':
          description: Пользователь авторизован
        '401':
          description: Пользователь не авторизован


components:
  schemas:
    createUser:
      type: object

      properties:
        email:
          type: string
          example: qwerty@htmlacademy.ru
          format: email

        name:
          type: string
          example: qwerty
          minLength: 1
          maxLength: 15

        password:
          type: string
          example: 123456
          minLength: 6
          maxLength: 12

        avatarUrl:
          type: string
          description: Аватар пользователя в формате .jpg или .png

        type:
          type: string
          description: Тип пользователя
          enum: [обычный, pro]

      required:
        - name
        - email
        - password
        - type

    user:
      type: object

      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        email:
          type: string
          example: qwerty@htmlacademy.ru
          description: Электронная почта пользователя
          format: email

        name:
          type: string
          description: Имя пользователя
          minLength: 1
          maxLength: 15

        avatarUrl:
          type: string
          description: Аватар пользователя в формате .jpg или .png

        type:
          type: string
          description: Тип пользователя
          enum: [обычный, pro]

    login:
      type: object

      properties:
        email:
          type: string
          format: email
        password:
          type: string

      required:
        - email
        - password

    token:
      type: object

      properties:
        token:
          type: string
          description: "Токен для авторизации пользователя"

    createOffer:
      type: object

      properties:
        title:
          type: string
          description: Наименование
          minLength: 10
          maxLength: 100
        description:
          type: string
          description: Описание предложения
          minLength: 20
          maxLength: 1024
        createdDate:
          type: string
          format: date
          description: Дата публикации предложения
        city:
          type: string
          description: Город. Один из шести городов.
          enum: [Paris, Cologne, Dusseldorf, Amsterdam, Hamburg, Brussels]
        previewImage:
          type: string
          description: Превью изображения
        images:
          type: array
          items:
            type: string
          description: Фотографии жилья
        houseType:
          type: string
          description: Тип жилья
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
          description: Количество комнат
          minimum: 1
          maximum: 8
        guests:
          type: integer
          description: Количество гостей
          minimum: 1
          maximum: 10
        price:
          type: integer
          description: Стоимость аренды
          minimum: 100
          maximum: 100000
        goods:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
          description: Удобства. Список удобств
        author:
          $ref: '#/components/schemas/user'
        coordinates:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
          description: Координаты предложения для аренды
      required:
        - title
        - description
        - createdDate
        - city
        - previewImage
        - images
        - houseType
        - bedrooms
        - guests
        - price
        - goods
        - author
        - coordinates

    offer:
      type: object
      properties:
        title:
          type: string
          description: Наименование
          minLength: 10
          maxLength: 100
        description:
          type: string
          description: Описание предложения
          minLength: 20
          maxLength: 1024
        createdDate:
          type: string
          format: date
          description: Дата публикации предложения
        city:
          type: string
          description: Город, в котором находится предложение
          enum: [Paris, Cologne, Dusseldorf, Amsterdam, Hamburg, Brussels]
        previewImage:
          type: string
          description: Превью изображения
        images:
          type: array
          items:
            type: string
          description: Фотографии жилья
        rating:
          type: number
          description: Рейтинг предложения
          minimum: 1
          maximum: 5
          example: 4.5
        isPremium:
          type: boolean
          description: Премиальность предложения
        isFavorite:
          type: boolean
          description: Предложение находится в избранном у пользователя
        houseType:
          type: string
          description: Тип жилья
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
          description: Количество комнат
          minimum: 1
          maximum: 8
        guests:
          type: integer
          description: Количество гостей
          minimum: 1
          maximum: 10
        price:
          type: integer
          description: Стоимость аренды
          minimum: 100
          maximum: 100000
        goods:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
          description: Удобства. Список удобств
        author:
          $ref: '#/components/schemas/user'
        coordinates:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
          description: Координаты предложения для аренды
        commentsCount:
          type: number

    shortOffer:
      type: object
      properties:
        title:
          type: string
          description: Наименование
          minLength: 10
          maxLength: 100
        city:
          type: string
          description: Город, в котором находится предложение
          enum: [Paris, Cologne, Dusseldorf, Amsterdam, Hamburg, Brussels]
        previewImage:
          type: string
          description: Превью изображения
        createdDate:
          type: string
          format: date
          description: Дата публикации предложения
        rating:
          type: number
          description: Рейтинг предложения
          minimum: 1
          maximum: 5
          example: 4.5
        isPremium:
          type: boolean
          description: Премиальность предложения
        isFavorite:
          type: boolean
          description: Предложение находится в избранном у пользователя
        houseType:
          type: string
          description: Тип жилья
          enum: [apartment, house, room, hotel]
        price:
          type: integer
          description: Стоимость аренды
          minimum: 100
          maximum: 100000
        commentsCount:
          type: number

    comment:
      type: object
      properties:
        text:
          type: string
          description: Текст комментария
          minLength: 5
          maxLength: 1024
        createdDate:
          type: string
          format: date
          description: Дата публикации комментария
        rating:
          type: number
          description: Рейтинг комментария
          minimum: 1
          maximum: 5
        author:
          $ref: '#/components/schemas/user'
